using UnityEditor;
using UnityEngine;

namespace ProjectGuild.View
{
    /// <summary>
    /// Custom editor for NodeSceneRoot with tools for directional spawn points.
    ///
    /// Features:
    /// - "Auto-Generate Directional Spawn Points" button: creates 8 child Transforms
    ///   in a circle around the scene focal point at a configurable radius.
    /// - Scene View gizmos: colored spheres for directional spawn points, deposit point,
    ///   and spawn points.
    /// </summary>
    [CustomEditor(typeof(NodeSceneRoot), true)]
    public class NodeSceneRootEditor : Editor
    {
        private static readonly Color DirectionalSpawnColor = new(1f, 0.6f, 0.1f); // Orange
        private static readonly Color SpawnPointColor = new(0.2f, 0.8f, 1f);       // Cyan
        private static readonly Color DepositPointColor = new(0.2f, 1f, 0.4f);     // Green
        private static readonly Color FocalPointColor = Color.yellow;
        private const float GizmoSphereRadius = 0.4f;
        private const float LabelOffsetY = 1.5f;

        private float _generateRadius = 15f;

        public override void OnInspectorGUI()
        {
            DrawDefaultInspector();

            var sceneRoot = (NodeSceneRoot)target;

            EditorGUILayout.Space(12);
            EditorGUILayout.LabelField("Directional Spawn Tools", EditorStyles.boldLabel);

            _generateRadius = EditorGUILayout.FloatField("Generate Radius", _generateRadius);

            if (GUILayout.Button("Auto-Generate Directional Spawn Points", GUILayout.Height(28)))
            {
                AutoGenerateDirectionalSpawns(sceneRoot, _generateRadius);
            }

            if (sceneRoot.DirectionalSpawnPoints != null && sceneRoot.DirectionalSpawnPoints.Length > 0)
            {
                EditorGUILayout.HelpBox(
                    $"{sceneRoot.DirectionalSpawnPoints.Length} directional spawn points configured. " +
                    "Nudge positions in Scene View as needed.",
                    MessageType.Info);
            }
            else
            {
                EditorGUILayout.HelpBox(
                    "No directional spawn points. Entrance nodes don't need them. " +
                    "For circumference/area nodes, click the button above to auto-generate.",
                    MessageType.None);
            }
        }

        private void AutoGenerateDirectionalSpawns(NodeSceneRoot sceneRoot, float radius)
        {
            const int pointCount = 8;

            Undo.RecordObject(sceneRoot, "Auto-Generate Directional Spawn Points");

            // Remove existing auto-generated points (if any)
            var existingPoints = sceneRoot.DirectionalSpawnPoints;
            if (existingPoints != null)
            {
                foreach (var point in existingPoints)
                {
                    if (point != null && point.gameObject.name.StartsWith("DirSpawn_"))
                        Undo.DestroyObjectImmediate(point.gameObject);
                }
            }

            // Create new points in a circle around the focal point
            Vector3 focalCenter = sceneRoot.SceneFocalPosition;
            var newPoints = new Transform[pointCount];

            for (int i = 0; i < pointCount; i++)
            {
                float angle = i * (2f * Mathf.PI / pointCount);
                float x = Mathf.Cos(angle) * radius;
                float z = Mathf.Sin(angle) * radius;

                var pointObj = new GameObject($"DirSpawn_{i}");
                Undo.RegisterCreatedObjectUndo(pointObj, "Create Directional Spawn Point");
                pointObj.transform.SetParent(sceneRoot.transform);
                pointObj.transform.position = focalCenter + new Vector3(x, 0f, z);
                newPoints[i] = pointObj.transform;
            }

            // Wire the array via serialized property
            var so = new SerializedObject(sceneRoot);
            var prop = so.FindProperty("_directionalSpawnPoints");
            prop.arraySize = pointCount;
            for (int i = 0; i < pointCount; i++)
                prop.GetArrayElementAtIndex(i).objectReferenceValue = newPoints[i];
            so.ApplyModifiedProperties();

            EditorUtility.SetDirty(sceneRoot);
            Debug.Log($"[NodeSceneRootEditor] Generated {pointCount} directional spawn points at radius {radius:F1}m around focal point.");
        }

        private void OnEnable()
        {
            SceneView.duringSceneGui += OnSceneGUI;
        }

        private void OnDisable()
        {
            SceneView.duringSceneGui -= OnSceneGUI;
        }

        private void OnSceneGUI(SceneView sceneView)
        {
            var sceneRoot = target as NodeSceneRoot;
            if (sceneRoot == null) return;

            // Draw focal point
            Handles.color = FocalPointColor;
            Handles.DrawSolidDisc(sceneRoot.SceneFocalPosition, Vector3.up, 0.3f);

            var labelStyle = new GUIStyle(EditorStyles.boldLabel)
            {
                normal = { textColor = Color.white },
                alignment = TextAnchor.MiddleCenter,
                fontSize = 10,
            };

            // Draw directional spawn points
            if (sceneRoot.DirectionalSpawnPoints != null)
            {
                Handles.color = DirectionalSpawnColor;
                for (int i = 0; i < sceneRoot.DirectionalSpawnPoints.Length; i++)
                {
                    var point = sceneRoot.DirectionalSpawnPoints[i];
                    if (point == null) continue;

                    Handles.SphereHandleCap(0, point.position, Quaternion.identity,
                        GizmoSphereRadius * 2f, EventType.Repaint);

                    // Dotted line from focal center
                    Handles.DrawDottedLine(sceneRoot.SceneFocalPosition, point.position, 4f);

                    // Label
                    labelStyle.normal.textColor = DirectionalSpawnColor;
                    Handles.Label(point.position + Vector3.up * LabelOffsetY, $"Dir {i}", labelStyle);
                }
            }

            // Draw regular spawn points
            if (sceneRoot.SpawnPoints != null)
            {
                Handles.color = SpawnPointColor;
                for (int i = 0; i < sceneRoot.SpawnPoints.Length; i++)
                {
                    var point = sceneRoot.SpawnPoints[i];
                    if (point == null) continue;

                    Handles.SphereHandleCap(0, point.position, Quaternion.identity,
                        GizmoSphereRadius * 2f, EventType.Repaint);

                    labelStyle.normal.textColor = SpawnPointColor;
                    Handles.Label(point.position + Vector3.up * LabelOffsetY, $"Spawn {i}", labelStyle);
                }
            }

            // Draw deposit point
            if (sceneRoot.DepositPointPosition.HasValue)
            {
                Handles.color = DepositPointColor;
                Vector3 depositPos = sceneRoot.DepositPointPosition.Value;
                Handles.SphereHandleCap(0, depositPos, Quaternion.identity,
                    GizmoSphereRadius * 2f, EventType.Repaint);

                labelStyle.normal.textColor = DepositPointColor;
                Handles.Label(depositPos + Vector3.up * LabelOffsetY, "Deposit", labelStyle);
            }
        }
    }
}
